import turtle
import time

from turtle import *
wn=turtle.Screen()
wn.bgcolor("black")
wn.title('Turtle')
skk=turtle.Turtle()
skk.pensize(5)
skk.penup()
skk.goto(0,200)
skk.pendown()
skk.pencolor('deeppink')
skk.right(60)
for i in range(4):
    if i==3:
        skk.penup()
        skk.setpos(-45,170)
        skk.pendown()
        skk.pencolor("white")
        skk.circle(50)
        skk.pencolor('deeppink')
        skk.penup()
        skk.setpos(0,200)
        skk.pendown()
    skk.forward(170)
    skk.right(120)
skk.pencolor('black')
skk.right(270)
skk.forward(20)
skk.pencolor('deeppink')
for i in range(4):
    if i==1:
        skk.forward(84)
        skk.color("white")
        skk.penup()
        skk.setpos(0, -85)
        skk.pendown()
        skk.circle(50)
        skk.color("deeppink")
        skk.penup()
        skk.setpos(0, -135)
        skk.pendown()
        skk.forward(84)
        skk.right(90)
    else:
        skk.forward(168)
        skk.right(90)

skk.fillcolor("goldenrod")
skk.pencolor('darkgoldenrod')
#1
skk.begin_fill()
skk.circle(43)
skk.end_fill()
skk.right(250)
skk.begin_fill()
for i in range(5):
    skk.pencolor('darkgoldenrod')
    skk.forward(80)
    skk.right(145)
skk.end_fill()
skk.right(170)
skk.pencolor('slategrey')
skk.forward(5)

#2
skk.pencolor('darkgoldenrod')
skk.right(60)
skk.begin_fill()
skk.circle(50)
skk.end_fill()
skk.right(270)
for i in range(4):
  skk.begin_fill()
  skk.forward(50)
  skk.right(120)
skk.end_fill()
for i in range(6):
  skk.begin_fill()
  skk.right(90)
  skk.forward(40)
  skk.end_fill()
#3

skk.penup()
skk.setpos(180,-90)
skk.pendown()
skk.right(-150)
skk.pencolor('darkgoldenrod')
skk.begin_fill()
skk.circle(50,180)
skk.left(90)
skk.forward(35)
skk.right(90)
skk.forward(30)
skk.left(180)
skk.circle(10,-180)
skk.left(180)
skk.circle(5,-180)
skk.circle(25,180)
skk.forward(30)
skk.right(88)
skk.forward(48)
skk.left(95)
skk.circle(60)
skk.end_fill()
skk.backward(10)
skk.right(110)
turtle.done()

